services:
  app:
    build: .
    container_name: python_app
    ports:
      - 1280:1280
    env_file:
      - .env
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - tennis_table_net
    restart: on-failure

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - :3306
    networks:
      - tennis_table_net
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
      start_period: 5s
networks:
  tennis_table_net:
    driver: bridge
volumes:
  mysql-volume:
