[tool.poetry]
name = "tennis-table"
version = "0.1.0"
description = ""
authors = ["Brokiloene <brklvn.minor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.31"
jinja2 = "^3.1.4"
waitress = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
