"""Init database

Revision ID: bf655d56e134
Revises: 
Create Date: 2024-09-08 21:55:57.449428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf655d56e134"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_name"), "player", ["name"], unique=False)
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.String(length=11), nullable=False),
        sa.ForeignKeyConstraint(["player1_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player2_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["winner_id"], ["player.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match")
    op.drop_index(op.f("ix_player_name"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
