name: Pytest

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Pytest check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root --with=dev

      - name: Create .env file from Secrets
        run: echo -e "${{ secrets.ENV }}" > .env
      - name: Load environment variables from .env
        uses: falti/dotenv-action@v1
        with:
          path: .env

      - name: Debug environment variables
        run: env
      - name: Check dir
        run: ls -a
      - name: Run tests with pytest
        run: PYTHONPATH=$(pwd) poetry run pytest
